//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DISCOUNT
    {
        public decimal DISCOUNT_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal ITEM_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public decimal USER_ID { get; set; }
    }
}
