//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_SELECT
    {
        public decimal SelectedId { get; set; }
        public decimal id { get; set; }
        public decimal name { get; set; }
        public decimal price { get; set; }
        public string pic { get; set; }
        public int quantity { get; set; }
        public decimal discount { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> totalDiscount { get; set; }
        public Nullable<int> availableQuantity { get; set; }
        public decimal CustomerID { get; set; }
    }
}
