//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PICTURE
    {
        public decimal PICTURE_ID { get; set; }
        public Nullable<decimal> ITEM_ID { get; set; }
        public string PICTURE_NAME { get; set; }
        public byte[] PICTURE { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATION_BY { get; set; }
        public string COMPUTER_NAME { get; set; }
    }
}
