//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_INFO
    {
        public decimal LOGIN_INFO_ID { get; set; }
        public string IP_ADDRESS { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan TIME { get; set; }
    }
}
