//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_ACCESS_POLICY
    {
        public decimal SYS_ACCP_ID { get; set; }
        public Nullable<decimal> USER_GROUP_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> SYS_MENU_ID { get; set; }
        public Nullable<System.DateTime> SYS_ACCESS_DATE { get; set; }
        public string SYS_ACCESS_TITLE { get; set; }
        public string SYS_MENU_FILE { get; set; }
        public Nullable<decimal> SYS_ACCESS_BY { get; set; }
    }
}
