//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_AUDIT_INFO
    {
        public decimal SYS_AUDIT_LOG_ID { get; set; }
        public Nullable<decimal> SYS_USER_ID { get; set; }
        public string OPERATION_TYPE { get; set; }
        public string SYS_AUDIT_NOTE { get; set; }
        public string OPERATION_BY { get; set; }
        public string OPERATION_DETAILS { get; set; }
        public string OPERATION_DATE { get; set; }
    }
}
