//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_CUSTOMER
    {
        public decimal CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string Password { get; set; }
        public bool ISLOGEDIN { get; set; }
    }
}
