//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_SALES_DETAILS
    {
        public decimal SALES_DETAILS_ID { get; set; }
        public Nullable<decimal> BILL_NO { get; set; }
        public Nullable<decimal> ITEM_ID { get; set; }
        public Nullable<decimal> SALES_QTY { get; set; }
        public Nullable<decimal> SALES_PRICE { get; set; }
    }
}
