//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_USER_GROUP
    {
        public decimal USER_GROUP_ID { get; set; }
        public string USER_GROUP_NAME { get; set; }
        public string USER_GROUP_SHORT_NAME { get; set; }
        public string USER_GROUP_CODE { get; set; }
    }
}
