//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_DESIGNATION
    {
        public decimal DESIGNATION_ID { get; set; }
        public string DESIGNATION_NAME { get; set; }
        public byte[] DESIGNATION_CODE { get; set; }
    }
}
