//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_CONTACT
    {
        public decimal CONTACT_ID { get; set; }
        public Nullable<decimal> CONTACT_TYPE_ID { get; set; }
        public string CONTACT_INFO { get; set; }
        public Nullable<decimal> CONTACT_PERSON_ID { get; set; }
        public Nullable<decimal> USER_GROUP_ID { get; set; }
    }
}
