//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_SYS_USER
    {
        public decimal USER_ID { get; set; }
        public string USER_FULL_NAME { get; set; }
        public string USER_LOGIN_NAME { get; set; }
        public string USER_LOGIN_PASSWORD { get; set; }
        public Nullable<decimal> CREATION_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> USER_DESIGNATION_ID { get; set; }
        public decimal BRANCH_ID { get; set; }
        public Nullable<decimal> USER_GROUP_ID { get; set; }
    }
}
