//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_BRANCH_INFO
    {
        public decimal BRANCH_ID { get; set; }
        public string BRANCH_TITLE { get; set; }
        public string BRANCH_SHORT_NAME { get; set; }
        public string BRANCH_CODE { get; set; }
        public Nullable<decimal> BRANCH_CONTACT_ID { get; set; }
        public Nullable<decimal> BRANCH_ADDRESS_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    }
}
