//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_THANA
    {
        public decimal THANA_ID { get; set; }
        public string THANA_NAME { get; set; }
        public string THANA_CODE { get; set; }
        public Nullable<decimal> DISTRICT_ID { get; set; }
    }
}
