//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_ORDER_DETAILS
    {
        public decimal ORDER_DETAILS_ID { get; set; }
        public Nullable<decimal> ORDER_ID { get; set; }
        public byte[] ORDER_LIST { get; set; }
    }
}
